modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="autocraft"
version="26.0.0.22"
displayName="AutoCraft"
displayURL="https://0.net"
logoFile="logo.png"
credits="-"
authors="LLZ_Argentum"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.autocraft]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.autocraft]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration